version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./config/:/config
      - /var/log/go-boiler/:/var/log/go-boiler/